build: java 설치 추가

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,11 +1,11 @@
-# github actions 에서 보이는 이름입니다
 name: deploy
 
 on:
   workflow_dispatch:
   push:
     branches:
-    - main
+      - main
+
 jobs:
   deploy:
     runs-on: self-hosted
@@ -16,17 +16,41 @@ jobs:
           sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/APT_AUCTION_API 
 
       - uses: actions/checkout@v3
-      - name: gradle bootjar
-        run: |
-          chmod +x ./gradlew
-          ./gradlew bootjar
-      - name: kill 8080 port if exist
+
+      - name: Set up JDK 21
+        uses: actions/setup-java@v3
+        with:
+          java-version: '21'
+          distribution: 'corretto'  # Amazon Corretto JDK 사용
+          cache: gradle
+
+      - name: Grant execute permission for gradlew
+        run: chmod +x ./gradlew
+
+      - name: Build with Gradle
+        run: ./gradlew bootjar
+
+      - name: Kill process on port 8080 if exists
         run: |
           if sudo lsof -i :8080; then
             echo "Port 8080 is already in use. Killing the process..."
             sudo lsof -i :8080 | awk 'NR!=1 {print $2}' | sudo xargs kill -9
           fi
 
-      - name: deploy
+      - name: Deploy application
         run: |
-          sudo java -jar build/libs/auction-api.jar --spring.profiles.active=prod &
+          nohup sudo java \
+          -jar build/libs/auction-api.jar \
+          --spring.profiles.active=prod \
+          > /home/ubuntu/auction-api.log 2>&1 &
+
+      - name: Check application health
+        run: |
+          echo "Waiting for application to start..."
+          sleep 30
+          if curl -f http://localhost:8080/actuator/health; then
+            echo "Application is healthy"
+          else
+            echo "Application failed to start"
+            exit 1
+          fi
